// @flow
// 生成物。書き換えず、`uf run pages` を走らせること。出典は各ページの front matter。

export type Heading = {| readonly id: string, readonly text: string |};

export type Page = {|
  readonly path: string,
  readonly title: string,
  readonly description: string,
  readonly section: string,
  readonly source: string,
  readonly headings: $ReadOnlyArray<Heading>,
|};

export const PAGES: $ReadOnlyArray<Page> = [
  {
    path: "/",
    title: "uflabo — uf（Uniflowed）日本語解説",
    description: "Flow で書く React のための統合ツールチェーン「uf」を、日本語でまるごと解説するサイト。",
    section: "intro",
    source: "",
    headings: [
      { id: "30-秒でわかる-uf", text: "30 秒でわかる uf" },
      { id: "どこから読むか", text: "どこから読むか" },
      { id: "1-ページだけ読むなら", text: "1 ページだけ読むなら" },
      { id: "このサイトについて", text: "このサイトについて" },
    ],
  },
  {
    path: "/intro/overview",
    title: "uf の全体像",
    description: "uf は「ツールチェーン」と「フレームワーク」の 2 つの顔を持つ。何を自分で持ち、何を他に任せているかを 1 ページで。",
    section: "intro",
    source: "/",
    headings: [
      { id: "一言でいうと", text: "一言でいうと" },
      { id: "2-つの顔", text: "2 つの顔" },
      { id: "パイプライン", text: "パイプライン" },
      { id: "何を自分で持たず何を持つか", text: "何を自分で持たず、何を持つか" },
      { id: "実行環境は-3-つに分かれる", text: "実行環境は 3 つに分かれる" },
      { id: "現在地2026-年-9-月", text: "現在地（2026 年 9 月）" },
      { id: "このサイトの構成", text: "このサイトの構成" },
    ],
  },
  {
    path: "/intro/glossary",
    title: "用語集",
    description: "uf のドキュメントに頻出する用語を、日本語の訳語と一緒に整理。",
    section: "intro",
    source: "",
    headings: [
      { id: "uf-固有の概念", text: "uf 固有の概念" },
      { id: "ルーティング", text: "ルーティング" },
      { id: "レンダリングサーバー", text: "レンダリング・サーバー" },
      { id: "flow", text: "Flow" },
      { id: "ツールチェーン", text: "ツールチェーン" },
    ],
  },
  {
    path: "/why/what-is-uf",
    title: "uf とは何か",
    description: "「ツールを組み合わせる」のではなく「1 つのツールチェーン」を選ぶという主張と、その代償。",
    section: "why",
    source: "/guide/why-uf",
    headings: [
      { id: "誰のためのページか", text: "誰のためのページか" },
      { id: "主張-パースは-1-回でいい", text: "主張: パースは 1 回でいい" },
      { id: "代償-正直に書かれている", text: "代償: 正直に書かれている" },
      { id: "どう決めるか要約", text: "どう決めるか（要約）" },
      { id: "次に読む", text: "次に読む" },
    ],
  },
  {
    path: "/why/why-flow",
    title: "なぜ Flow か",
    description: "React は Flow で書かれている。React をいちばんよく記述できる型システムは、ツールチェーンを持たない型システムだった。",
    section: "why",
    source: "/guide/why",
    headings: [
      { id: "一段落で言うと", text: "一段落で言うと" },
      { id: "flow-だけが言えること", text: "Flow だけが言えること" },
      { id: "flow-が言えないこと", text: "Flow が言えないこと" },
      { id: "なぜプラグインではなく丸ごとのツールチェーンなのか", text: "なぜプラグインではなく丸ごとのツールチェーンなのか" },
      { id: "次に読む", text: "次に読む" },
    ],
  },
  {
    path: "/why/flow-vs-typescript",
    title: "Flow と TypeScript",
    description: "TypeScript はほとんどの行で勝つ。Flow が勝つのは、React 自身が書かれた型システムだからこそ存在する 4 つの行。",
    section: "why",
    source: "/guide/typescript",
    headings: [
      { id: "前提", text: "前提" },
      { id: "typescript-が勝つ行", text: "TypeScript が勝つ行" },
      { id: "uf-が負ける行flow-ではなく-uf-の問題", text: "uf が負ける行（Flow ではなく uf の問題）" },
      { id: "dts-を出荷するパッケージ", text: ".d.ts を出荷するパッケージ" },
      { id: "flow-だけが綴れること", text: "Flow だけが綴れること" },
      { id: "なぜ-uf-を作れたのか", text: "なぜ uf を作れたのか" },
      { id: "どう決めるか", text: "どう決めるか" },
    ],
  },
  {
    path: "/why/compare",
    title: "他ツールとの比較",
    description: "create-react-app、Vite + React、Next.js、Bun と並べて。負ける行を勝つ行と同じ表に載せる。",
    section: "why",
    source: "/guide/compare",
    headings: [
      { id: "一画面版", text: "一画面版" },
      { id: "負ける行を先に読む", text: "負ける行を先に読む" },
      { id: "create-react-app-と比べて", text: "create-react-app と比べて" },
      { id: "vite--react-と比べて", text: "Vite + React と比べて" },
      { id: "nextjs-と比べて", text: "Next.js と比べて" },
      { id: "bun-と比べて", text: "Bun と比べて" },
      { id: "でどれを選ぶか", text: "で、どれを選ぶか" },
    ],
  },
  {
    path: "/why/vite-plus",
    title: "uf と Vite+",
    description: "いちばん比較されるツールチェーン。ただし答えている問いが違う。Vite+ は TypeScript ツールチェーンを統合し、uf は Flow の React 構文を使えるようにする。",
    section: "why",
    source: "/guide/vite-plus",
    headings: [
      { id: "uf-は-vite-の競合ではない", text: "uf は Vite の競合ではない" },
      { id: "違い", text: "違い" },
      { id: "typescript-ファーストが-flow-を書く人に課すもの", text: "「TypeScript ファースト」が Flow を書く人に課すもの" },
      { id: "vite-にあって-uf-にないもの", text: "Vite+ にあって uf にないもの" },
      { id: "uf-が正しい選択になるとき", text: "uf が正しい選択になるとき" },
      { id: "併用できるか", text: "併用できるか" },
    ],
  },
  {
    path: "/why/not-do",
    title: "uf がやらないこと",
    description: "木曜の午後に見つける境界は「制限」。始める前に読む同じ境界は「約束」。意図的な拒否と、issue 番号つきの未実装。",
    section: "why",
    source: "/guide/scope",
    headings: [
      { id: "拒否決定でありissue-で閉じることはない", text: "拒否（決定であり、issue で閉じることはない）" },
      { id: "まだできていないこと未完でありissue-がある", text: "まだできていないこと（未完であり、issue がある）" },
      { id: "拒否と未実装の見分け方", text: "拒否と未実装の見分け方" },
    ],
  },
  {
    path: "/why/architecture",
    title: "アーキテクチャとレッドライン",
    description: "uf は create-react-app と同じ「オールインワン」の形をしている。だから、自分に課した禁止事項と、まだ守れていない箇所を公開している。",
    section: "why",
    source: "/guide/architecture",
    headings: [
      { id: "create-react-app-の何がまずかったか", text: "create-react-app の何がまずかったか" },
      { id: "uf-の立ち位置", text: "uf の立ち位置" },
      { id: "レッドライン", text: "レッドライン" },
      { id: "性能もアーキテクチャの一部", text: "性能もアーキテクチャの一部" },
      { id: "まだ守れていない箇所", text: "まだ守れていない箇所" },
      { id: "検討対象外", text: "検討対象外" },
      { id: "レッドラインが防がない失敗", text: "レッドラインが防がない失敗" },
    ],
  },
  {
    path: "/start/install",
    title: "インストール",
    description: "uf は 1 つのネイティブバイナリ。JavaScript ホスト（Node.js / Bun / Deno）は必要だが、それ経由でインストールはしない。",
    section: "start",
    source: "/guide/install",
    headings: [
      { id: "必要なもの", text: "必要なもの" },
      { id: "リリースから入れる", text: "リリースから入れる" },
      { id: "nix-で", text: "Nix で" },
      { id: "ソースから", text: "ソースから" },
      { id: "javascript-ホスト", text: "JavaScript ホスト" },
      { id: "インストールの確認", text: "インストールの確認" },
    ],
  },
  {
    path: "/start/first-project",
    title: "最初のプロジェクト",
    description: "空のディレクトリからビルド済みサイトまで。書かれる 9 ファイルの全部を説明する。3 つはデモなので消す。",
    section: "start",
    source: "/guide/project",
    headings: [
      { id: "スキャフォールド", text: "スキャフォールド" },
      { id: "動かす", text: "動かす" },
      { id: "設定", text: "設定" },
      { id: "レイアウトとページ", text: "レイアウトとページ" },
      { id: "ビルド", text: "ビルド" },
      { id: "それ以外", text: "それ以外" },
      { id: "次に読む", text: "次に読む" },
    ],
  },
  {
    path: "/start/editors",
    title: "エディタ設定",
    description: "uf lsp は uf の言語サーバー。エディタが見せる lint と整形は、ターミナルの uf lint / uf fmt と同じクレートから来る。",
    section: "start",
    source: "/guide/editors",
    headings: [
      { id: "サーバーが答えるもの", text: "サーバーが答えるもの" },
      { id: "どの設定を読むか", text: "どの設定を読むか" },
      { id: "vs-code-と-cursor", text: "VS Code と Cursor" },
      { id: "neovim", text: "Neovim" },
      { id: "vim", text: "Vim" },
      { id: "helix", text: "Helix" },
      { id: "emacs", text: "Emacs" },
      { id: "zed", text: "Zed" },
    ],
  },
  {
    path: "/start/tutorial",
    title: "チュートリアル: 読書リストを作る",
    description: "uf new からアップロードできるディレクトリまで。ルーティング、レイアウト、ローダー、共有状態、アクセシブルなタブ、バリデーション付きフォーム、そのテスト。",
    section: "start",
    source: "/guide/tutorial",
    headings: [
      { id: "何を作るか", text: "何を作るか" },
      { id: "スキャフォールド", text: "スキャフォールド" },
      { id: "データ", text: "データ" },
      { id: "一覧ページ", text: "一覧ページ" },
      { id: "記事ページ", text: "記事ページ" },
      { id: "レイアウト", text: "レイアウト" },
      { id: "2-つのコンポーネントが共有する状態", text: "2 つのコンポーネントが共有する状態" },
      { id: "キーボードで使えるタブ", text: "キーボードで使えるタブ" },
      { id: "フォーム", text: "フォーム" },
      { id: "テスト", text: "テスト" },
      { id: "チェックと整形", text: "チェックと整形" },
      { id: "ビルド", text: "ビルド" },
      { id: "動かなかったこと", text: "動かなかったこと" },
    ],
  },
  {
    path: "/app/flow-syntax",
    title: "Flow のモダンな構文",
    description: "component, hook, renders, match, enum。それぞれ何のためにあり、uf が Vite に渡す前に何へ変換するか。",
    section: "app",
    source: "/guide/flow",
    headings: [
      { id: "component", text: "component" },
      { id: "hook", text: "hook" },
      { id: "renders", text: "renders" },
      { id: "match", text: "match" },
      { id: "enum", text: "enum" },
      { id: "uf-がすべてに対してすること", text: "uf がすべてに対してすること" },
    ],
  },
  {
    path: "/app/routing",
    title: "ルーティング",
    description: "app/ 配下のファイルがルートテーブル。書くべきルート設定も、ディレクトリと同期させるリストもない。",
    section: "app",
    source: "/guide/routing",
    headings: [
      { id: "予約されたファイル名", text: "予約されたファイル名" },
      { id: "パス", text: "パス" },
      { id: "レイアウトはネストする", text: "レイアウトはネストする" },
      { id: "テンプレートは再マウントする", text: "テンプレートは再マウントする" },
      { id: "並行ルートスロット", text: "並行ルート（スロット）" },
      { id: "インターセプトルート", text: "インターセプトルート" },
      { id: "not-found-もネストする", text: "not-found もネストする" },
      { id: "ページが-throw-したとき", text: "ページが throw したとき" },
      { id: "ページがまだ解決中のとき", text: "ページがまだ解決中のとき" },
      { id: "データの読み込み", text: "データの読み込み" },
      { id: "メタデータ", text: "メタデータ" },
      { id: "ナビゲーション", text: "ナビゲーション" },
      { id: "リダイレクトリライトレスポンスヘッダ", text: "リダイレクト、リライト、レスポンスヘッダ" },
      { id: "ベースパスと末尾スラッシュ", text: "ベースパスと末尾スラッシュ" },
      { id: "ルートはいつ描画されるか", text: "ルートはいつ描画されるか" },
      { id: "ルートの型", text: "ルートの型" },
    ],
  },
  {
    path: "/app/requests",
    title: "リクエストに答える",
    description: "ミドルウェア、ルートハンドラ、ドラフトモード、QUERY メソッド、そしてストリーム・ソケット・レスポンスより長生きする仕事。",
    section: "app",
    source: "/guide/routing/requests",
    headings: [
      { id: "ミドルウェア", text: "ミドルウェア" },
      { id: "ルートハンドラ", text: "ルートハンドラ" },
      { id: "ドラフトモード", text: "ドラフトモード" },
      { id: "query-url-に収まらなかった-get", text: "QUERY: URL に収まらなかった GET" },
      { id: "ストリームソケットレスポンスより長生きする仕事", text: "ストリーム、ソケット、レスポンスより長生きする仕事" },
    ],
  },
  {
    path: "/app/rendering",
    title: "レンダリングモード",
    description: "ドキュメントはどこから来るのか、リンクをクリックしたら何が起きるのか。2 つの問いに 2 つの設定で答える。",
    section: "app",
    source: "/guide/rendering",
    headings: [
      { id: "2-つの軸", text: "2 つの軸" },
      { id: "ルートの決定", text: "ルートの決定" },
      { id: "isr-再生成されるページ", text: "isr: 再生成されるページ" },
      { id: "ビルドを読む", text: "ビルドを読む" },
      { id: "デプロイの形を選ぶ", text: "デプロイの形を選ぶ" },
      { id: "ページはどう遷移するか", text: "ページはどう遷移するか" },
      { id: "navigation-document", text: "navigation: \"document\"" },
      { id: "csr-シングルページアプリケーション", text: "csr: シングルページアプリケーション" },
      { id: "ドキュメント遷移を選ぶとき", text: "ドキュメント遷移を選ぶとき" },
    ],
  },
  {
    path: "/app/server-components",
    title: "Server Components",
    description: "uf アプリのすべてのモジュールは、そう言わない限りサーバーのもの。\\\"use client\\\" がそう言う方法で、その価値は慣習ではなくグラフが決める。",
    section: "app",
    source: "/guide/server-components",
    headings: [
      { id: "現在の契約", text: "現在の契約" },
      { id: "3-種類のモジュール", text: "3 種類のモジュール" },
      { id: "境界は-import", text: "境界は import" },
      { id: "グラフが決めること", text: "グラフが決めること" },
      { id: "分割はルート単位", text: "分割はルート単位" },
      { id: "何が動いたか見る", text: "何が動いたか見る" },
      { id: "報告するもの", text: "報告するもの" },
      { id: "uf-lint-の位置", text: "uf lint の位置" },
      { id: "ここにないもの", text: "ここにないもの" },
    ],
  },
  {
    path: "/app/async-react",
    title: "非同期 React",
    description: "Suspense、transition、楽観的 UI は 1 つの問いへの 3 つの答え。「他の仕事がまだ終わっていない間、読者に何を見せるべきか」。",
    section: "app",
    source: "/guide/async-react",
    headings: [
      { id: "地図", text: "地図" },
      { id: "ルートの-suspense", text: "ルートの Suspense" },
      { id: "suspense-ではないもの", text: "Suspense ではないもの" },
      { id: "transition", text: "Transition" },
      { id: "楽観的-ui", text: "楽観的 UI" },
      { id: "フォームと-action", text: "フォームと Action" },
      { id: "境界を選ぶ", text: "境界を選ぶ" },
    ],
  },
  {
    path: "/app/server-actions",
    title: "Server Actions",
    description: "use server\\\" の export は、ブラウザがネットワーク越しに呼べる関数。ビルドに含まれた瞬間から公開 HTTP エンドポイントだ。",
    section: "app",
    source: "/guide/server-actions",
    headings: [
      { id: "書く", text: "書く" },
      { id: "呼ぶ", text: "呼ぶ" },
      { id: "フォーム", text: "フォーム" },
      { id: "越えられるもの", text: "越えられるもの" },
      { id: "呼び出しとエンドポイント", text: "呼び出しとエンドポイント" },
      { id: "アクションは自分で認可する", text: "アクションは自分で認可する" },
      { id: "idそして何が呼べるのか", text: "id、そして何が呼べるのか" },
      { id: "失敗について何も返ってこない", text: "失敗について何も返ってこない" },
      { id: "ワイヤーが必要とする型", text: "ワイヤーが必要とする型" },
      { id: "ここにないもの", text: "ここにないもの" },
    ],
  },
  {
    path: "/app/state",
    title: "状態管理（@uniflowed/state）",
    description: "atom。モジュールスコープで宣言し、どこからでも読み書きでき、マウントする Provider はない。Jotai を知っていれば形は分かる。意図的に違うのは 4 つ。",
    section: "app",
    source: "/guide/state",
    headings: [
      { id: "1-つのオーバーロードではなく-4-つのコンストラクタ", text: "1 つのオーバーロードではなく 4 つのコンストラクタ" },
      { id: "react-なしで", text: "React なしで" },
      { id: "react-で", text: "React で" },
      { id: "派生合成逃げ道", text: "派生、合成、逃げ道" },
      { id: "非同期-atom-は-suspense-ではなく値", text: "非同期 atom は Suspense ではなく値" },
      { id: "書き込みが何をするか", text: "書き込みが何をするか" },
      { id: "永続化された状態", text: "永続化された状態" },
      { id: "下の層", text: "下の層" },
      { id: "jotai-から来る人へ", text: "Jotai から来る人へ" },
    ],
  },
  {
    path: "/app/forms",
    title: "フォーム（@uniflowed/form）",
    description: "React Hook Form の機能リストを、Proxy なしで。非制御入力、狭い購読、型付きの値、配線済みのアクセシブルなエラー。そして本家がゼロにする場所で 1 回描画する、その理由。",
    section: "app",
    source: "/guide/form",
    headings: [
      { id: "フォーム", text: "フォーム" },
      { id: "useform-が返すもの", text: "useForm が返すもの" },
      { id: "フィールドをその型で読む", text: "フィールドをその型で読む" },
      { id: "後から届く値", text: "後から届く値" },
      { id: "ルール", text: "ルール" },
      { id: "ルールの代わりにスキーマ", text: "ルールの代わりにスキーマ" },
      { id: "サーバーアクションへ送信", text: "サーバーアクションへ送信" },
      { id: "値が描画される場所で購読する", text: "値が描画される場所で購読する" },
      { id: "フィールドの配列", text: "フィールドの配列" },
      { id: "制御コンポーネント", text: "制御コンポーネント" },
      { id: "非同期バリデーション", text: "非同期バリデーション" },
      { id: "react-hook-form-から来る人へ", text: "React Hook Form から来る人へ" },
    ],
  },
  {
    path: "/app/effects",
    title: "Effect（@uniflowed/effect）",
    description: "失敗を型に入れる。Effect<A, E, R> は何を生み、どう失敗し、何を必要とするかを言う。Effect-TS のモデルから、Flow が持たない高階型に由来する部分を除いたもの。",
    section: "app",
    source: "/guide/effect",
    headings: [
      { id: "3-つのチャネル", text: "3 つのチャネル" },
      { id: "合成", text: "合成" },
      { id: "回復", text: "回復" },
      { id: "並行性", text: "並行性" },
      { id: "リソース", text: "リソース" },
      { id: "リトライ", text: "リトライ" },
      { id: "サービス", text: "サービス" },
      { id: "effect-ts-から来る人へ", text: "Effect-TS から来る人へ" },
    ],
  },
  {
    path: "/app/ui",
    title: "ヘッドレスコンポーネント（@uniflowed/ui）",
    description: "ロービングタブストップ、フォーカストラップ、タイプアヘッド、ライブリージョン、フォーム配線、モーダル、テーブル。そしてそれぞれを真にする ARIA。スタイルは一切なし。",
    section: "app",
    source: "/guide/ui",
    headings: [
      { id: "得るもの得ないもの", text: "得るもの、得ないもの" },
      { id: "所有かヘッドレスか", text: "所有かヘッドレスか" },
      { id: "パートが描画する要素を変える", text: "パートが描画する要素を変える" },
      { id: "field", text: "Field" },
      { id: "tabs", text: "Tabs" },
      { id: "dialog", text: "Dialog" },
      { id: "menu", text: "Menu" },
      { id: "combobox", text: "Combobox" },
      { id: "checkbox-と-switch", text: "Checkbox と Switch" },
      { id: "パッケージ全体で成り立つ-4-つのルール", text: "パッケージ全体で成り立つ 4 つのルール" },
    ],
  },
  {
    path: "/app/styling",
    title: "スタイリングとコンテンツ",
    description: "CSS、StyleX とそのトークン、ダークモード、Markdown と MDX、ビルド時のシンタックスハイライト。どれもオンにしなくても動く。",
    section: "app",
    source: "/guide/styling",
    headings: [
      { id: "css", text: "CSS" },
      { id: "stylex-とトークン", text: "StyleX とトークン" },
      { id: "markdown-と-mdx", text: "Markdown と MDX" },
      { id: "シンタックスハイライト", text: "シンタックスハイライト" },
      { id: "公開ファイル", text: "公開ファイル" },
    ],
  },
  {
    path: "/app/assets",
    title: "画像、フォント、アイコン、カード",
    description: "画像を import すればレイアウトが求める幅にリサイズされ、フォントを import すればセルフホストされ同じ幅を占めるフォールバックと組にされ、アイコンを import すればビルドが到達した集合だけの 1 スプライトに入る。すべてビルド時に uf の中で。",
    section: "app",
    source: "/guide/assets",
    headings: [
      { id: "画像", text: "画像" },
      { id: "フォント", text: "フォント" },
      { id: "アイコン", text: "アイコン" },
      { id: "open-graph-カード", text: "Open Graph カード" },
      { id: "設定", text: "設定" },
      { id: "開発とビルドは一致する", text: "開発とビルドは一致する" },
      { id: "やらないこと", text: "やらないこと" },
    ],
  },
  {
    path: "/app/caching",
    title: "キャッシュ",
    description: "ルートキャッシュと fetch キャッシュ。どちらもデフォルト off で、ルート・リクエストごとに opt-in。時間ベースの再検証と、タグやパスによるオンデマンド無効化。名指ししなければ 1 プロセスのメモリ内。",
    section: "app",
    source: "/guide/cache",
    headings: [
      { id: "オンにする", text: "オンにする" },
      { id: "2-つの数字の意味", text: "2 つの数字の意味" },
      { id: "オンデマンドで無効化", text: "オンデマンドで無効化" },
      { id: "決してキャッシュされないもの", text: "決してキャッシュされないもの" },
      { id: "fetch-キャッシュ", text: "fetch キャッシュ" },
      { id: "どこに住むか", text: "どこに住むか" },
      { id: "プリレンダリング済みページの再生成", text: "プリレンダリング済みページの再生成" },
      { id: "何の価値があるか", text: "何の価値があるか" },
      { id: "ブラウザで", text: "ブラウザで" },
      { id: "ここにないもの", text: "ここにないもの" },
    ],
  },
  {
    path: "/app/auth",
    title: "サインイン（OAuth）",
    description: "uf は OAuth フローを出荷し、OAuth プロバイダは出荷しない。ポータブルなのはリダイレクト、state、トークン交換、セッション。ポータブルでないのはどの URL に話し、トークンをどう人に変えるか。",
    section: "app",
    source: "/guide/auth",
    headings: [
      { id: "プロバイダ", text: "プロバイダ" },
      { id: "4-つのハンドラ", text: "4 つのハンドラ" },
      { id: "誰がサインインしているか読む", text: "誰がサインインしているか読む" },
      { id: "ストア", text: "ストア" },
      { id: "uf-が拒否するもの", text: "uf が拒否するもの" },
    ],
  },
  {
    path: "/app/logging",
    title: "ロギング",
    description: "人が読む行とログ集約器が読む行は別の行で、両方を持つ方法はレコードを組んで 2 度フォーマットすること。すべてのリクエストは到着時に id を得る。",
    section: "app",
    source: "/guide/logging",
    headings: [
      { id: "何か言う", text: "何か言う" },
      { id: "リクエスト-id", text: "リクエスト id" },
      { id: "リクエストが残す行", text: "リクエストが残す行" },
      { id: "フォーマットとレベル", text: "フォーマットとレベル" },
      { id: "別の場所へ送る", text: "別の場所へ送る" },
      { id: "ログ行が運んではならないもの", text: "ログ行が運んではならないもの" },
    ],
  },
  {
    path: "/app/vitals",
    title: "Web Vitals",
    description: "LCP、CLS、INP、TTFB、FCP をブラウザ自身の PerformanceObserver から読み、あなたが渡すコールバックに 1 つずつ渡す。デフォルトの送信先もサードパーティもなく、書くまでリクエストは出ない。",
    section: "app",
    source: "/guide/vitals",
    headings: [
      { id: "api-の全体", text: "API の全体" },
      { id: "得るもの", text: "得るもの" },
      { id: "どこかへ送る", text: "どこかへ送る" },
      { id: "マシンを離れるもの", text: "マシンを離れるもの" },
      { id: "web-vitals-と数字が違う場所", text: "web-vitals と数字が違う場所" },
      { id: "計測できないブラウザ", text: "計測できないブラウザ" },
      { id: "開発中", text: "開発中" },
    ],
  },
  {
    path: "/targets/deploy",
    title: "Web ビルドをデプロイする",
    description: "ビルドがデプロイするもの。変わるのはリクエストに答えるマシンがすでに何を持っているか。このチェックアウト、JavaScript ランタイム、プラットフォームランタイム、静的ファイルホスト、あるいは 1 つの実行ファイルだけ。",
    section: "targets",
    source: "/guide/deploy",
    headings: [
      { id: "形を選ぶ", text: "形を選ぶ" },
      { id: "一度ビルドする", text: "一度ビルドする" },
      { id: "出す前に確認する", text: "出す前に確認する" },
      { id: "ホスト向けにパッケージする", text: "ホスト向けにパッケージする" },
      { id: "static-はファイルだけ", text: "static はファイルだけ" },
      { id: "1-ファイルにコンパイルする", text: "1 ファイルにコンパイルする" },
      { id: "起動時の環境", text: "起動時の環境" },
      { id: "確立されていること", text: "確立されていること" },
    ],
  },
  {
    path: "/targets/react-native",
    title: "React Native ターゲット",
    description: "React Native は uf の「ターゲット」であり、Web アプリを横向きにするフラグではない。共有部分は Flow ツールチェーンとファイルシステムルートテーブル。ネイティブ部分は Metro バンドル、プラットフォーム別ルートファイル、ナビゲータ契約、DOM を装わないテストクエリ。",
    section: "targets",
    source: "/guide/react-native",
    headings: [
      { id: "現在地", text: "現在地" },
      { id: "使える範囲", text: "使える範囲" },
      { id: "ターゲットを設定する", text: "ターゲットを設定する" },
      { id: "ルートファイル", text: "ルートファイル" },
      { id: "metro", text: "Metro" },
      { id: "デバイスで開発する", text: "デバイスで開発する" },
      { id: "ネイティブナビゲーション", text: "ネイティブナビゲーション" },
      { id: "テスト", text: "テスト" },
      { id: "ネイティブコードの-lint", text: "ネイティブコードの lint" },
      { id: "expo-と比べて", text: "Expo と比べて" },
      { id: "まだ欠けているもの", text: "まだ欠けているもの" },
    ],
  },
  {
    path: "/targets/tui",
    title: "ターミナル UI（@uniflowed/tui）",
    description: "ターミナルをホストにした React。ページ用に書くのと同じコンポーネント・hook・状態・effect を、flexbox でレイアウトしセルとして描く。差分は変わったセルだけを送る。",
    section: "targets",
    source: "/guide/tui",
    headings: [
      { id: "アプリケーション全体", text: "アプリケーション全体" },
      { id: "opentui-に従う", text: "OpenTUI に従う" },
      { id: "変わったセルだけ", text: "変わったセルだけ" },
      { id: "react-ink-と計測", text: "React Ink と計測" },
      { id: "画面に収まらないもの", text: "画面に収まらないもの" },
      { id: "キーボードとフォーカス", text: "キーボードとフォーカス" },
      { id: "マウス", text: "マウス" },
      { id: "テキスト選択", text: "テキスト選択" },
      { id: "あなたのと違うことのできるターミナル", text: "あなたのと違うことのできるターミナル" },
      { id: "ターミナルなしでテスト", text: "ターミナルなしでテスト" },
      { id: "なぜ-rust-ではなく-javascript-か", text: "なぜ Rust ではなく JavaScript か" },
      { id: "まだないもの", text: "まだないもの" },
    ],
  },
  {
    path: "/toolchain/dev-build",
    title: "dev と build",
    description: "どちらも Vite。uf は Vite に何を渡すか決め、JavaScript ホスト上で起動し、プロトコルで運転する。フォークもラップも再実装もしない。",
    section: "toolchain",
    source: "/guide/dev",
    headings: [
      { id: "どう組み合わさるか", text: "どう組み合わさるか" },
      { id: "uf-dev", text: "uf dev" },
      { id: "ハイドレーションが失敗したとき", text: "ハイドレーションが失敗したとき" },
      { id: "uf-build", text: "uf build" },
      { id: "uf-を越えて手を伸ばす", text: "uf を越えて手を伸ばす" },
    ],
  },
  {
    path: "/toolchain/fmt-lint",
    title: "フォーマットとリント",
    description: "どちらもコンパイラと同じ木を読む。フォーマッタは Meta の Flow パーサーの上の Rust プリンタ。リンタは uf 自身のルールと Flow の組み込み lint と React Compiler の診断を 1 パス・1 レポートで走らせる。",
    section: "toolchain",
    source: "/guide/format",
    headings: [
      { id: "uf-fmt", text: "uf fmt" },
      { id: "uf-lint", text: "uf lint" },
      { id: "uf-check", text: "uf check" },
      { id: "ci-で", text: "CI で" },
    ],
  },
  {
    path: "/toolchain/check",
    title: "型チェック",
    description: "uf check は uf lint に Flow の型推論を続けたもの。Meta 自身の Flow を Rust に移植してバイナリにコンパイルしたもので、uf にあなたの型についての第 2 の意見はない。",
    section: "toolchain",
    source: "/guide/check",
    headings: [
      { id: "走らせる", text: "走らせる" },
      { id: "何をチェックするか", text: "何をチェックするか" },
      { id: "import-は何に解決されるか", text: "import は何に解決されるか" },
      { id: "ライブラリ定義と-flowconfig", text: "ライブラリ定義と .flowconfig" },
      { id: "機械が読むレポート", text: "機械が読むレポート" },
      { id: "速度", text: "速度" },
      { id: "エラーを-1-つ黙らせる", text: "エラーを 1 つ黙らせる" },
      { id: "ここにないもの", text: "ここにないもの" },
    ],
  },
  {
    path: "/toolchain/testing",
    title: "テスト",
    description: "uf test は JavaScript ワーカーを持つ Rust ランナー。何が、どの順で、何コアで走り、レポートが何を言うかを Rust が決め、本体はホストが走らせる。JavaScript を実行することだけが Rust にできないから。",
    section: "toolchain",
    source: "/guide/testing",
    headings: [
      { id: "性能モデル", text: "性能モデル" },
      { id: "テストを書く", text: "テストを書く" },
      { id: "モジュールを置き換える", text: "モジュールを置き換える" },
      { id: "走らせる", text: "走らせる" },
      { id: "カバレッジ", text: "カバレッジ" },
      { id: "bun-との位置", text: "Bun との位置" },
    ],
  },
  {
    path: "/toolchain/dependencies",
    title: "依存管理",
    description: "uf はパッケージを解決も取得もしない。uf install や uf add はプロジェクトがすでに使っているパッケージマネージャを見つけて実行し、その前にポリシーを置く。install スクリプトは拒否、CI でズレたロックファイルは拒否、コマンドを持たないマネージャは「持たない」と言う。",
    section: "toolchain",
    source: "/guide/dependencies",
    headings: [
      { id: "どのマネージャが走るか", text: "どのマネージャが走るか" },
      { id: "インストール", text: "インストール" },
      { id: "ci-では-ロックファイルが固定するものを正確に", text: "CI では: ロックファイルが固定するものを正確に" },
      { id: "スクリプト", text: "スクリプト" },
      { id: "追加と削除", text: "追加と削除" },
      { id: "ツリーについて尋ねる", text: "ツリーについて尋ねる" },
      { id: "更新", text: "更新" },
      { id: "レジストリと出所", text: "レジストリと出所" },
      { id: "ここにないもの", text: "ここにないもの" },
    ],
  },
  {
    path: "/toolchain/environments",
    title: "環境（ランタイムと .env）",
    description: "1 つの答えで 2 つの問い。各コマンドがどの Node / Bun / pnpm で走るか、そして process.env と import.meta.env の値がどこから来るか。",
    section: "toolchain",
    source: "/guide/env",
    headings: [
      { id: "ツールを宣言する", text: "ツールを宣言する" },
      { id: "最初の実行", text: "最初の実行" },
      { id: "何が走るか見る", text: "何が走るか見る" },
      { id: "先にインストールする", text: "先にインストールする" },
      { id: "コマンドの外でツールを使う", text: "コマンドの外でツールを使う" },
      { id: "envtoolchain-からの移行", text: "env.toolchain からの移行" },
      { id: "ここでやらないこと", text: "ここでやらないこと" },
      { id: "どのファイルをどの順で", text: "どのファイルを、どの順で" },
    ],
  },
  {
    path: "/toolchain/tasks",
    title: "タスク（uf run / ufx）",
    description: "uf install は scripts のある package.json を拒否するので、uf プロジェクトの自動化は uf.config.js に tasks として住む。uf run は 1 つと、それが依存するすべてを、依存順に、複数同時に、宣言した入力が変わっていなければキャッシュから走らせる。",
    section: "toolchain",
    source: "/guide/tasks",
    headings: [
      { id: "宣言する", text: "宣言する" },
      { id: "1-つとそれが依存するものを走らせる", text: "1 つと、それが依存するものを走らせる" },
      { id: "コマンドがどう走るか", text: "コマンドがどう走るか" },
      { id: "キャッシュ", text: "キャッシュ" },
      { id: "失敗したとき", text: "失敗したとき" },
      { id: "始まる前に拒否されるもの", text: "始まる前に拒否されるもの" },
      { id: "ワークスペース", text: "ワークスペース" },
      { id: "command-のないタスク", text: "command のないタスク" },
      { id: "ufx-パッケージのバイナリ", text: "ufx: パッケージのバイナリ" },
      { id: "ここにないもの", text: "ここにないもの" },
    ],
  },
  {
    path: "/toolchain/ci",
    title: "CI で uf を動かす",
    description: "GitHub Actions、GitLab CI、CircleCI。どれもツールチェーンをインストールする 1 ステップで、どれも薄い。3 つとも人間が走らせるのと同じインストーラを走らせるから。",
    section: "toolchain",
    source: "/guide/ci",
    headings: [
      { id: "github-actions", text: "GitHub Actions" },
      { id: "gitlab-ci", text: "GitLab CI" },
      { id: "circleci", text: "CircleCI" },
      { id: "チェックの前にインストールする", text: "チェックの前にインストールする" },
      { id: "バージョンを固定する", text: "バージョンを固定する" },
      { id: "ジョブから結果を読む", text: "ジョブから結果を読む" },
      { id: "何をキャッシュしキーが何を言わなければならないか", text: "何をキャッシュし、キーが何を言わなければならないか" },
      { id: "実際に走っているもの", text: "実際に走っているもの" },
      { id: "コミットの前にも", text: "コミットの前にも" },
      { id: "ここにないもの", text: "ここにないもの" },
    ],
  },
  {
    path: "/toolchain/agents",
    title: "エージェント（uf mcp）",
    description: "uf mcp は Model Context Protocol を stdio で提供する。コーディングエージェントが人と同じチェック（lint、型チェック、テスト、ルートテーブル）を走らせ、CI が読むのと同じ JSON レポートを読める。8 ツール、うち 2 つが書く。",
    section: "toolchain",
    source: "/guide/agents",
    headings: [
      { id: "登録する", text: "登録する" },
      { id: "ツール", text: "ツール" },
      { id: "呼び出しが返すもの", text: "呼び出しが返すもの" },
      { id: "エージェントが仮定してはならないこと", text: "エージェントが仮定してはならないこと" },
    ],
  },
  {
    path: "/toolchain/migrate",
    title: "既存アプリの移行",
    description: "create-react-app から、Vite + React から、Next.js から。そのまま持ち越せるもの、手順、移行後も残る差分。uf migrate コマンドはまだないので（#970）、すべて手作業。",
    section: "toolchain",
    source: "/guide/migrate",
    headings: [
      { id: "始める前の-4-つの問い", text: "始める前の 4 つの問い" },
      { id: "すべての移行に共通するもの", text: "すべての移行に共通するもの" },
      { id: "create-react-app-から", text: "create-react-app から" },
      { id: "vite--react-から", text: "Vite + React から" },
      { id: "nextjs-から", text: "Next.js から" },
      { id: "自分の移行を見積もる", text: "自分の移行を見積もる" },
    ],
  },
  {
    path: "/reference/cli",
    title: "コマンド一覧",
    description: "サブコマンド、主なフラグ、終了コード。グローバルフラグはサブコマンドの前、サブコマンド自身のフラグは後に置く。",
    section: "reference",
    source: "/reference/cli",
    headings: [
      { id: "グローバルフラグ", text: "グローバルフラグ" },
      { id: "プロジェクトを作る", text: "プロジェクトを作る" },
      { id: "調べる", text: "調べる" },
      { id: "開発とビルド", text: "開発とビルド" },
      { id: "チェック", text: "チェック" },
      { id: "依存", text: "依存" },
      { id: "環境とタスク", text: "環境とタスク" },
      { id: "ui-とその他", text: "UI とその他" },
      { id: "終了コード", text: "終了コード" },
    ],
  },
  {
    path: "/reference/config",
    title: "uf.config.js 設定リファレンス",
    description: "唯一の設定ファイル。Flow なので defineConfig が書いた場所で型チェックし、すべてのキーにデフォルトがある。",
    section: "reference",
    source: "/reference/config",
    headings: [
      { id: "トップレベル", text: "トップレベル" },
      { id: "runtime-と-packagemanager", text: "runtime と packageManager" },
      { id: "app", text: "app" },
      { id: "build", text: "build" },
      { id: "dev", text: "dev" },
      { id: "fmt-と-lint", text: "fmt と lint" },
      { id: "test", text: "test" },
      { id: "env", text: "env" },
      { id: "pm", text: "pm" },
      { id: "非推奨キーの扱い", text: "非推奨キーの扱い" },
    ],
  },
  {
    path: "/reference/packages",
    title: "パッケージ一覧",
    description: "すべての @uniflowed/* パッケージ、何のためか、そして本当に存在するか。素の Flow で、ネイティブバインディングはない。",
    section: "reference",
    source: "/reference/packages",
    headings: [
      { id: "コア", text: "コア" },
      { id: "アプリケーション", text: "アプリケーション" },
      { id: "データ", text: "データ" },
      { id: "インターフェース", text: "インターフェース" },
      { id: "テスト", text: "テスト" },
      { id: "ツーリング", text: "ツーリング" },
      { id: "uniflowedui-が今日出荷しているもの", text: "@uniflowed/ui が今日出荷しているもの" },
      { id: "公開状況", text: "公開状況" },
    ],
  },
  {
    path: "/reference/std",
    title: "標準ライブラリ（@uniflowed/std）",
    description: "Go の標準ライブラリを基準に、JavaScript が持たない部分を Flow で。1 モジュール 1 export パス、なのでプログラムは import した分だけ払う。",
    section: "reference",
    source: "/reference/std",
    headings: [
      { id: "今日出荷されているもの", text: "今日出荷されているもの" },
      { id: "型が要点", text: "型が要点" },
      { id: "キャンセル-なぜ-abortsignal-だけではないのか", text: "キャンセル: なぜ AbortSignal だけではないのか" },
      { id: "どこで走るか", text: "どこで走るか" },
      { id: "なぜ-rust-ではなく-javascript-か", text: "なぜ Rust ではなく JavaScript か" },
      { id: "go-の標準ライブラリの地図", text: "Go の標準ライブラリの地図" },
      { id: "地図が古くならない場所", text: "地図が古くならない場所" },
    ],
  },
];
